### PR TITLE
Fix 35

### PR DESCRIPTION
**Pull request by LeilyR**
fixed get_Chromosome_size()

### CODE REVIEW

**Comment by lldelisle** [comment]
Just to understand, the goal is that get_Chromosome_size return the number of bases which are covered instead of the size of the chromosome?
For me this is a different information and it should get a new name, no?
In pyGenomeTracks, we are using get_Chromosome_size to check that the user does not want to plot something above the end of the chromosome.

**Comment by LeilyR** [comment]
Yes that is the goal, because when matrices are pruned, using `hicAdjustMatrix`, this function is not working properly to handle the length of the chromosomes and returns corrupted plots , that is how I initially spotted it. Surely, it will not going to work as it intends to  else where on the same sort of matrices too. This change should not pass the end of chromosome at all, if that is what you are worried about. All I did was that give it the actual length which can be computed from the first bin and the last bin of a chromosome, instead of simply considering the value of last bin as the length. This is still to me the size of a chromosome as has been used in matrix. However I know that this may brings up modification in several other places , that is why I kept it here as an open PR and I am indeed open to discussion.

**Comment by lldelisle** [comment]
- Just to make it clear get_chromosome_sizes was giving before the maximum coordinate used in the matrix and would now give the actual spread of the chromosome.
What happens if you have:
```
    new_cut_intervals = [('a', 10, 20, 1), ('b', 0, 10, 1),
                         ('b', 20, 30, 1), ('c', 30, 40, 1), ('c', 40, 90, 1)]

```
What size do you expect for `'b'`? 22 or 31?

- In pyGenomeTracks, I think it is fine for the last version (because I changed a raise to warning) but for previous versions it will raise an error all the time that is what annoy me... But I can write a FAQ in the pyGenomeTracks documentation.
I think the main problem is that there was no documentation on this method.

**Comment by LeilyR** [comment]
The way it is now , would generate 31 but we do not generate this type of matrix to begin with, do we?

**Comment by lldelisle** [comment]
I think if they are in `cool` format and one bin has no value, the bin is set as `nan_bin` and then if we do `hic_ma.maskBins(hic_ma.nan_bins)` the `self.cut_intervals` is updated and can contains holes.

**Comment by LeilyR** [comment]
I found the order strange, Does this mean that chromosome a is between two bins of chromosome b?

**Comment by lldelisle** [comment]
No, this was just an example, it could be:
```
    new_cut_intervals = [('a', 100, 200, 1), ('b', 0, 10, 1),
                         ('b', 20, 30, 1), ('c', 300, 340, 1), ('c', 340, 390, 1)]
```
But you are right, this should not happen when we load a standard Hi-C matrix, however, it could be possible, I think with non regular Hi-C matrix...

**Comment by joachimwolff** [comment]
Is this read to merge?

**Pull request merged**
