### PR TITLE
Release 17

### PR DESCRIPTION
**Pull request by lldelisle**
To be compatible with new numpy releases.

### CODE REVIEW

**Comment by lldelisle** [comment]
Who wants to review? @bgruening @LeilyR ?

**Review by bgruening — COMMENTED** [review]
I guess we should drop python 3.6 and maybe add 3.10. Otherwise, it looks good to me.

Do we need to specify >numpy somewhere?

**Review by bgruening — APPROVED** [review]
Gracias!

**Comment by lldelisle** [comment]
I cannot merge... Would you mind to do it and to release on pypi please (this is not part of the CI)?

**Comment by bgruening** [comment]
>Would you mind to do it and to release on pypi please

That one I'm not sure and yes we should add it as GH action.

**Pull request merged**
